EverestAPI/SpringCollab2020

Ahorn/entities/caveWall.jl
Ahorn/lang/en_gb.lang
CaveWall.cs
Entities/CaveWall.cs
SpringCollab2020.csproj

The entity appears solid when the player is not in it, but fades out once a player enters it, similarly to how FakeWalls work. It then fades back in after the player leaves it again.
Adjacent CaveWalls blend together
Closes #7

Added CaveWall entity

---

Ahorn/lang/en_gb.lang
Ahorn/triggers/smoothCameraOffsetTrigger.jl
Triggers/SmoothCameraOffsetTrigger.cs

Added Smooth Camera Offset Triggers

---

Ahorn/entities/floatierSpaceBlock.jl
Entities/FloatierSpaceBlock.cs
SpringCollab2020Module.cs

Floaty Space Blocks with a multiplier for how far they sink.
Closes #11

Floatier space block

---

Ahorn/entities/floatierSpaceBlock.jl
Ahorn/lang/en_gb.lang
Entities/FloatierSpaceBlock.cs

Floatier space blocks now move an appropriate amount further when you dash into them and how fast they bounce back after can be set in Ahorn.

Floatier space block dash fix

---

Entities/CaveWall.cs

Cave walls merge with Cave Walls with different fillTiles and no longer fade out when the player dies in them

Slight Fix for Cave Walls

---

Ahorn/entities/variableCrumble.jl
Ahorn/lang/en_gb.lang
Entities/VariableCrumbleBlock.cs

Adds a crumble block variant that allows you to configure the timer that it takes for the blocks to fall down.
Fixes #22

Variable Crumble Blocks

---

Ahorn/entities/bubbleReturnBerry.jl
Entities/BubbleReturnBerry.cs

A strawberry (also available as a winged strawberry) which when picked up transports the player back to their spawnpoint via bubble (similar to Cassettes and keys.)
Requested by LethargicDoggo and Mun in collabcord
Fixes #29

Berry with Return

---

Entities/InvisibleLightSource.cs

I fixed an issue with the light source where it doesn't work anywhere except for rooms located at 0,0. I am dumb.

Light source fix

---

Ahorn/entities/moveBlockBarrier.jl
Entities/MoveBlockBarrier.cs
Entities/MoveBlockBarrierRenderer.cs
SpringCollab2020Module.cs

A barrier that Madeline can go through, but not move blocks.
Closes #37

Move block barrier

---

Ahorn/entities/lightningDashSwitch.jl
Entities/LightningDashSwitch.cs

A Dash Switch which, instead of opening gates, removes the lightning in the room. Other than that it's the same...

Lightning Dash Switch

---

Entities/UpsideDownJumpThru.cs

Using Spring Collab 2020 on Linux causes the game to crash, due to an issue with hooking the `Player.OnCollideV` method.
... turns out this method is actually stored in the Player object as a delegate, in the `onCollideV` variable. This variable is initialized in the constructor, and it is used when collisions occur. So, hooking the constructor and modifying this variable to "wrap" it has the same effect as hooking `Player.OnCollideV`. And doesn't crash on Linux.

Work around game crashes on Linux caused by hooking Player.OnCollideV

---

Ahorn/lang/en_gb.lang
Ahorn/triggers/disableIcePhysics.jl
Entities/DisableIcePhysicsTrigger.cs
SpringCollab2020Module.cs
SpringCollab2020Session.cs
Triggers/DisableIcePhysicsTrigger.cs

Closes #75.
Pretty much patches the exact code pointed at by the issue, and saves the current enabled status in mod session.

Disable Ice Physics Trigger

---

Entities/FlagTouchSwitch.cs

Same as #98 but with puffer fish... _this time_ I checked, and nothing else triggers touch switches.

Have puffer fish explosions turn on flag touch switches

---

Ahorn/entities/multiNodeMovingPlatform.jl
Ahorn/lang/en_gb.lang
Entities/MultiNodeMovingPlatform.cs

Closes #100.
A moving platform, except with multiple nodes to travel between. Attributes are move time, pause time, and different "modes", allowing the platform to loop between nodes, cross all of them at once, etc.

Multi-node moving platforms

---

Entities/BubblePushField.cs

Fixes a crash which happens when the player dies inside of a bubble column.

Fix crash when player dies

---

Ahorn/lang/en_gb.lang
Ahorn/triggers/musicLayerFadeTrigger.jl
Triggers/MusicLayerFadeTrigger.cs

Closes #130.
This trigger fades a specific music layer.
Very similar to Everest's Music Layer Trigger, with attribute names based on the Music Fade Trigger.

Music Layer Fade Trigger

---

Ahorn/entities/flagToggleStarRotateSpinner.jl
Ahorn/lang/en_gb.lang
Entities/FlagToggleStarRotateSpinner.cs

Closes #149.
Basically the same as the other flag-toggled things from the collab helper.

Flag-toggled rotating stars (Star Rotate Spinners)

---

Ahorn/lang/en_gb.lang
Ahorn/triggers/strawberryCollectionField.jl
Triggers/StrawberryCollectionField.cs

Strawberry Collection Field

---

Ahorn/lang/en_gb.lang
Ahorn/triggers/lightningStrikeTrigger.jl
Triggers/LightningStrikeTrigger.cs

A few additions to the lightning strike trigger for Canadian's map:
- Constant lightning strikes when player is inside trigger
- Configurable height/Y offset for lightning strike

Lightning strike additions

---

Ahorn/triggers/swapDashTrigger.jl
SpringCollab2020Module.cs
Triggers/SwapDashTrigger.cs

"Swap Dash Trigger" comes from deskilln's Expert map, and the scale attribute for the decal registry comes from CANADIAN's grandmaster map. Those currently ship as 2 separate DLLs in the map pack, which is kind of messy.

Integrate map specific code mods

---

Ahorn/entities/foregroundReflectionTentacles.jl
Entities/ForegroundReflectionTentacles.cs

That's the Reflection Tentacles entity, except all layers are in the foreground (in front of fg tiles).

Foreground tentacles

---

Ahorn/entities/nonCoreModeWallBooster.jl
Ahorn/lang/en_gb.lang
Entities/NonCoreModeWallBooster.cs

Same as a wall booster, except it doesn't react to core mode changes. As simple as that.

Non-Core Mode Wall Booster

---

Ahorn/triggers/musicAreaChangeTrigger.jl
Triggers/MusicAreaChangeTrigger.cs

hastily written trigger to use for exit lobby music. reduces the number of triggers needed for rooms.
im no c# programmer so be gentle. should be good enough for its use case.

add music area change trigger

---

Ahorn/effects/customSnow.jl
Ahorn/lang/en_gb.lang
Effects/CustomSnow.cs
SpringCollab2020Module.cs

Small request to make the gyms look better. This is just an effect that extends Snow, and replaces the vanilla colors in its constructor, the rest of the effect is handled by the vanilla class.

Snow effect with custom colors
