Ahorn/lang/en_gb.lang, Ahorn/triggers/noRefillField.jl, SpringCollab2020Module.cs, Triggers/NoRefillField.cs
Entering the trigger turns `NoRefills` in inventory to true, and exiting it turns it back to false, giving the expected effect: killing ground refills while you are in the field's area.
Closes #6
=> No Refill Field trigger (closes #6)

.github/workflows/autobuild.yml
Who decided that auto-deleting branches were a good idea with gh-actions and that the workflow editor can't create a branch without a PR ._.
=> Update GitHub Actions autobuild workflow

Ahorn/lang/en_gb.lang, Ahorn/triggers/removeLightSourcesTrigger.jl, SpringCollab2020Module.cs, Triggers/RemoveLightSourcesTrigger.cs
When inside, deactivates all BloomPoints and LightVertexes in the current screen. Upon exiting, all become reactivated.
If it is marked as persistent, the lights will ALWAYS stay off  in every room in that level once the player goes inside of the trigger. (Including after Save and Quits and room transitions)
Code is a bit spaghetti though 😬
=> Add Remove Light Source Trigger

Ahorn/entities/sidewaysJumpThru.jl, Ahorn/lang/en_gb.lang, Entities/SidewaysJumpThru.cs, SpringCollab2020Module.cs
Closes #20.
This time, I didn't make it extend JumpThru, since those have little in common (... the _orientation_ to begin with: jump thrus extend on their width).
Most of how it works is an IL patch applied on multiple methods, that adds collide checks against sideways jumpthrus everywhere the game checks for solids. This way, Madeline can climb on and walljump off sideways jumpthrus.
(Note to self: the Julia part seems to need a tab to space pass.)
=> Sideways jumpthrus

Ahorn/entities/crystalBombDetonator.jl, Entities/CrystalBombDetonator.cs, Entities/CrystalBombDetonatorRenderer.cs, SpringCollab2020Module.cs
A field to be placed as Seeker Barriers would, used for detonating Crystal Bombs thrown/carried into them much like they are used to destroy Jellyfish.
Closes #62.
It's a bit of a disgusting hack, but it works, dammit.
=> Crystal Bomb (Cavern Helper) Detonation Field

Entities/CaveWall.cs
Before, cave walls would fade out when the player transitioned into them. Now, they're already invisible until the player leaves them.
=> Made Cave Walls vanish immediately when the player transitions into them

Entities/FlagTouchSwitch.cs, SpringCollab2020Module.cs
Just a small oversight, since the seekers check for collision with touch switches themselves.
=> Make seeker explosions trigger flag touch switches

Ahorn/entities/instantFallingBlock.jl, Ahorn/lang/en_gb.lang, Entities/InstantFallingBlock.cs
Closes #94.
Falling Blocks, except they don't wait for the player to fall, they are triggered right away.
=> Instant Falling Blocks

Ahorn/entities/groupedTriggerSpikes.jl, Ahorn/lang/en_gb.lang, Entities/GroupedTriggerSpikes.cs
Closes #90.
Based on Trigger Spikes from Everest, but edited to make all spikes rise at the same time when the player leaves the group.
Again, lots of copy-pastes, both on the Ahorn and on the C# side.
=> Grouped trigger spikes

Ahorn/entities/moveBlockCustomSpeed.jl, Ahorn/lang/en_gb.lang, Entities/MoveBlockCustomSpeed.cs
Closes #72.
The Ahorn part is just a copy-paste from the vanilla entity code, with the "fast" attribute replaced with a "moveSpeed" attribute for more customization. The default value is the "slow" vanilla speed.
In the C# part, I chose to "wrap" the Controller method, since the speed is set in the middle of this routine, and it is _200 lines long_. The private `targetSpeed` attribute is set just after a `yield return 0.2f;`, so this is how the wrapper knows this value might have to be changed. This limits the number of operations done with reflection.
=> Move Block with customizable speed

Ahorn/entities/noDashRefillSpring.jl, Ahorn/lang/en_gb.lang, Entities/NoDashRefillSpring.cs
Closes #70.
This is just a spring that looks like a vanilla spring and acts like it, with the only difference being the player collider. This one ensures that your dash count is intact even after bouncing on the spring.
=> No dash refill spring

Entities/UpsideDownJumpThru.cs
Fixes upside-down jumpthrus if Extended Variants are loaded **after** Spring Collab 2020. Extended Variants have an IL hook on the Player constructor.
=> Fix patch order for upside-down jumpthru player constructor patch

Ahorn/entities/customBirdTutorial.jl, Ahorn/lang/en_gb.lang, Ahorn/triggers/customBirdTutorial.jl, Entities/CustomBirdTutorial.cs, Triggers/CustomBirdTutorialTrigger.cs
Closes #60.
A tutorial bird that shows an arbitrary button combination. The tutorial bubble shows up when the player enters a trigger, and the bird flies away when the player enters another trigger. The "bird ID" is only useful if multiple birds are in the same room, to bind birds to triggers.
Vanilla allows for various things to be put in tutorial bird bubbles: textures, buttons, directions and strings. The "controls" parameter is quite complex, but powerful, as a result. The default value matches the vanilla hyperjump tutorial.
=> Bird tutorial with custom text and controls

Entities/BubbleReturnBerry.cs, Entities/SafeRespawnCrumble.cs
Include two different fixes:
* **Linux crashes with NullReferenceException when the player is squished**: same issue as #95, same workaround applied as #95. 
* **Linux crashes with no error log at the end of cassette flying**: we blamed that on the fact that the `CassetteFlyEnd` method is empty, and that some low-level limitations cause this crash when the method is hooked. The workaround here is to hook `CassetteFlyCoroutine` instead.
=> Fix crashes on cassette fly and on squish on Linux

Ahorn/entities/bubblePushField.jl, Ahorn/lang/en_gb.lang, Entities/BubblePushField.cs
Closes part of #102, core switch part should be coming in Pandora's Box.
Adds two new attributes for Bubble Push Fields: "activationMode" and "flag". This allows to set up bubble push fields to be only active when a certain session flag is set, or not set. The default value ("Always") matches their current behavior, so this shouldn't break existing maps.
=> Add flag activation options to Bubble Push Fields

Ahorn/lang/en_gb.lang
Closes #107 
Adds the following tooltips:
Bubble Return Berry
- winged
- checkpointID
- order
Glass Berry
- checkpointID
- order
Lightning Dash Switch
- side
- sprite
- persistent
=> Add missing tooltips to en_gb.lang

Entities/MoveBlockBarrier.cs
JaThePlayer reported a crash when bouncing off of a 3x spring, grabbing a jellyfish, and transitioning to another room. I supplied the necessary correction.
Waiting on JaThePlayer to confirm it's fixed.
=> Added null checks to MoveBlockBarrier to avoid potential crashes

Ahorn/lang/en_gb.lang, Ahorn/triggers/removeLightSourcesTrigger.jl, Triggers/RemoveLightSourcesTrigger.cs
Cookie (who I made this trigger for) discovered that some objects would later re-enable or create new light sources, which the trigger would not handle.
The trigger now disables the bloom renderer, and sets the alpha value of all VertexLights to 0f when lights are disabled. This might(?) cause a bit of a performance hit, but it's the most orthodox solution I could think of.
=> Fix remove light source trigger

Ahorn/lang/en_gb.lang, Ahorn/triggers/lightningStrikeTrigger.jl, Triggers/LightningStrikeTrigger.cs
Adds a lightning strike trigger, which upon entering, creates a flash of lightning on the screen. There are also additional options:
- Add the rain ambience to the level, as initially requested (toggleable per trigger)
- Create a white flash on the screen when the lightning strikes (toggleable per trigger)
- X offset of the lightning relative to the player
- Delay for the lightning strike after entering the trigger
- The seed used to randomized the nodes/path of the lightning strike
Closes #4
=> Add lightning strike trigger

Ahorn/entities/cassetteFriendlyStrawberry.jl, Ahorn/lang/en_gb.lang, Entities/CassetteFriendlyStrawberry.cs, Entities/CassetteFriendlyStrawberrySeed.cs
Closes #86.
Strawberry seeds but with two tweaks:
- when uncollected, their depth is 11. The maximum depth for active cassette blocks is 10, so this is just behind that.
- they don't attach to platforms. No idea why they attach to platforms in vanilla in the first place, but we don't want the side-effects of it for cassette blocks (seeds disappear with the block, and their hitbox is twice as big... for some reason). This is done by removing the `StaticMover` component.
=> Cassette-friendly strawberry seeds

Ahorn/lang/en_gb.lang, Ahorn/triggers/madelineSilhouetteTrigger.jl, SpringCollab2020Module.cs, SpringCollab2020Session.cs, Triggers/MadelineSilhouetteTrigger.cs
Closes #115.
Just a trigger turning Madeline into a tutorial ghost version of herself. There are missing sprites for some things, but this shouldn't matter for Bob Dole's map, because it relies on hard speed tech, so it has no swimming for example.
=> Madeline Silhouette Trigger

Triggers/RemoveLightSourcesTrigger.cs
This took way longer than it should have, and features even more spaghetti than before! Fixes a bug involving hooking the same method multiple times + also creates an exemption for payphone lights.
=> Update RemoveLightSourceTrigger again

Triggers/RemoveLightSourcesTrigger.cs
If you enter a room with a payphone but without lights being disabled, the game will crash. This fixes that.
=> Fix crash with payphone hook

Ahorn/entities/rainbowSpinnerColorController.jl, Ahorn/lang/en_gb.lang, Entities/RainbowSpinnerColorController.cs
Closes #69.
Drop a "rainbow spinner color controller" in a room with vanilla rainbow spinners to mod their color with a custom gradient.
If two controllers are present in two adjacent rooms with different parameters, spinners will fade between both parameters.
The CrystalStaticSpinner.GetHue is hooked on demand when a controller is loaded, and unhooked when the last controller is unloaded.
The default parameters attempt to emulate the gradient for vanilla spinners (which is a hue shift).
=> Rainbow Spinner Color Controller

Entities/SidewaysJumpThru.cs
Everest 1432 just came out, adding a patch on the `UpdateSprite` method. After looking over all mods I have installed, 2 mods are impacted by the code of `UpdateSprite` being moved to `orig_UpdateSprite`: Extended Variants and Spring Collab 2020. Extended Variants already got updated for this (version 0.14.2), and here is the fix for Spring Collab 2020.
=> Move hooks on UpdateSprite to orig_UpdateSprite on Everest 1432+

Ahorn/entities/flagToggleStarTrackSpinner.jl, Ahorn/entities/flagToggleWater.jl, Ahorn/entities/flagToggleWaterfall.jl, Ahorn/lang/en_gb.lang, Entities/FlagToggleComponent.cs, Entities/FlagToggleStarTrackSpinner.cs, Entities/FlagToggleWater.cs, Entities/FlagToggleWaterfall.cs
Small request from Bissy on Discord: be able to make the flag-toggled entities _disappear_ when a flag is active. This is done via an "inverted" checkbox, that inverts the flag's logic.
=> 'Inverted' checkbox for flag-toggled entities

Ahorn/entities/litBlueTorch.jl, Entities/LitBlueTorch.cs
Very small request from RealVet on Discord.
Torches in Temple have a `startLit` attribute, but that also makes them yellow. This one is blue. That's pretty much it.
That `startLit` attribute is checked twice: in the constructor to make it yellow, and in Added to light it right away and make it non-collidable. So, turning the attribute on at the beginning of `Added` does the trick.
=> Blue Torch that starts off lit

Ahorn/triggers/blockJellySpawnTrigger.jl, SpringCollab2020Module.cs, Triggers/BlockJellySpawnTrigger.cs
Closes #151.
That's a pretty specific request, but that's what DanTKO wants: when Madeline respawns inside one of those triggers, all jellies in the room shouldn't spawn. (they are actually removed right away, but the effect is the same.)
=> Block Jelly Spawn Trigger

Entities/GroupedTriggerSpikes.cs
Closes #137.
LedgeBlocker is a component tagging entities that should block Madeline from "climb hopping" (jumping when reaching the top of a wall).
Grouped trigger spikes should do that when they are extended. This PR aims at that. [Here is a video of this PR in action.](https://cdn.discordapp.com/attachments/663508177181999136/691326933509603348/Celeste_2020-03-22_17-42-05.mp4)
=> Block climbing on top of extended grouped trigger spikes

Ahorn/entities/customizableGlassBlock.jl, Ahorn/lang/en_gb.lang, Entities/CustomizableGlassBlock.cs
Requested by NeoKat (via direct ping to me) on Discord. The glass block background has depth -9990, fgtiles have depth -10000.
=> Add option to make glass block outlines appear behind fg tiles

Entities/BubblePushField.cs
Changes stupid mistake that causes bubbles to move and disappear based off the height of bubble columns rather than their width if they are left-facing.
=> Fix bubbles disappearing early in left-facing bubble columns

Entities/FlagToggleComponent.cs, Entities/FlagToggleStarRotateSpinner.cs, Entities/FlagToggleStarTrackSpinner.cs, Entities/FlagToggleWaterfall.cs
Spinners aren't updated at all during screen transitions, so we should hide them when they are added if we want to hide them during transitions.
Water and waterfalls are updated (they are tagged with TransitionUpdate), so water doesn't cause any issue. Waterfalls spawn some particles before they get disabled, so we need to turn them off early as well.
=> Hide flag-toggled entities properly on transitions when flag is disabled

Ahorn/entities/seekerCustomColors.jl, Ahorn/entities/seekerStatueCustomColors.jl, Ahorn/lang/en_gb.lang, Entities/SeekerCustomColors.cs, Entities/SeekerStatueCustomColors.cs
Request from TheAdvertisement on Discord.
Basically, particles are static attributes used when the seeker is updated. Those modded seekers swap out vanilla particles with custom colored counterparts at the beginning of their Update() method, and places them back at the end. This is enough to mod those particles' colors while not impacting other seekers (multiple, vanilla and modded, can be on-screen at the same time).
=> Seeker with custom particles and trail color

Entities/SeekerCustomColors.cs, SpringCollab2020Module.cs
The tricky part here is that the particles that appear when stomping a seeker don't get generated in a method that gets called during Seeker.Update()... but during Player.Update(). So, I used a hook to wrap the vanilla method that generates those particles instead.
=> Fix stomp particle color for seekers with custom colors

Entities/UnderwaterSwitchController.cs
Madeline was briefly coming out of water when respawning: there was no water between the respawn and the first time the underwater switch controller got updated.
To fix this, water gets spawned in the underwater switch controller's Added method if the flag is already active when it spawns.
=> Underwater Switch Controller: Fix 'Madeline coming out of water' sound effect when respawning underwater

Ahorn/entities/customRespawnTimeRefill.jl, Ahorn/lang/en_gb.lang, Entities/CustomRespawnTimeRefill.cs
This works the same as a vanilla refill, except the respawn time is different. This differs from "Plus One Refill" from Frost Helper (which has a custom respawn time too) because Plus One Refill is capped to the player's max dashes, unlike the vanilla double refills.
=> Refill with custom respawn time

Ahorn/entities/rainbowSpinnerColorAreaController.jl, Ahorn/lang/en_gb.lang, Entities/RainbowSpinnerColorAreaController.cs, Entities/RainbowSpinnerColorController.cs
Same principle as Rainbow Spinner Color Controller, but controlling spinners colliding with the area of the controller.
This was made into a separate entity, since
- the controller is room-wide and is point-based, the area controller is rectangle-based
- the controller has some logic to fade the spinner colors if two successive rooms have different settings, which is not required here: we just want the spinners within an area to have a certain color.
=> Rainbow Spinner Color Area Controller

Ahorn/entities/caveWall.jl, Ahorn/lang/en_gb.lang, Entities/CaveWall.cs
Per Cruor's request, add an option to prevent Cave Walls from fading in or out during transitions.
=> Add a disableTransitionFading attribute to Cave Walls

Ahorn/lang/en_gb.lang, Ahorn/triggers/cameraCatchupSpeed.jl, SpringCollab2020Module.cs, Triggers/CameraCatchupSpeedTrigger.cs
Requested, tested and approved by CANADIAN on Discord.
This PR adds a trigger that changes how fast the camera eases to its target. This is useful in situations with extremely fast speed (that is, for example, "reverse hyper off of a kevin into several ultras") where Madeline would just outrun the camera, needing weird workarounds like using growing camera offsets.
=> Camera Catchup Speed Trigger (for high speed situations)

Ahorn/entities/customSoundBerry.jl, Entities/CustomSoundBerry.cs
This is a copypaste of the Strawberry class with sounds made customizable. Since this is a discardable entity, I made near 0 effort to clean up decompiler stuff. This is just here to help making sounds for the silver berry, speed berry and such, and won't ship with the collab.
=> Sound Test Berry: berry with customizable sounds

Entities/CustomBirdTutorial.cs
2 things in one:
- if the info text is empty, shrink the bubble to only have it have 1 line of text.
- when the bubble width is computed, every text part in controls counts for the text width. But, when it is rendered, the text is offset by 1px on the right, and actually makes the following be offset by the text width **+ 1**. The more text parts are used, the more that offset is visible (here each "A" is a separate text part):
To compensate, this PR adds 1 to the bubble width for each text part. 1 more pixel is added if the first part is a text part, so that the bigger padding on the left is applied on the right as well.
This fix will be copied to Everest if this is merged here.
=> Custom Bird Tutorial: adjust width and height of bubble more accurately

Entities/FlagToggleWaterfall.cs, Entities/UnderwaterSwitchController.cs
There was a crash in this specific case:
- when waterfall spawns, the whole level is underwater (underwater switch controller), so the waterfall is "hitting" that water
- you hit a switch, making the waterfall appear and making the level not underwater anymore
- the waterfall wants to spawn particles on top of the water spawned by the underwater switch controller, since it is hitting it
- crash because it has no top
This PR works around that by computing the height / associated water pool when the waterfall is first turned on. In this situation, that means that the water spawned by the underwater switch controller is turned off when this computation occurs, and as such won't interfere.
=> Fix flag toggle waterfall crash when used with underwater switch controller

Ahorn/lang/en_gb.lang, Ahorn/triggers/colorGradeFadeTrigger.jl, SpringCollab2020Module.cs, Triggers/ColorGradeFadeTrigger.cs
Requested by Linj on Discord.
This works by hijacking the game's own "fade between 2 color grades" mechanic when transitioning from a color grade to another (normally happens when using `Level.NextColorGrade`). Except we are controlling the lerp value ourselves depending on the player position.
=> Color Grade Fade Trigger: fade between 2 color grades

Ahorn/effects/heatWaveNoColorGrade.jl, Effects/HeatWaveNoColorGrade.cs, SpringCollab2020Module.cs
A quite... specific request. For lobbies, it would be quite handy to have a heatwave effect that doesn't always mess with the color grade. The vanilla heatwave effect forces the color grade to "none" if it is not visible.
This PR adds a heatwave effect that is just the vanilla one, except it forces the colorgrade not to be changed by vanilla heatwave when it is fading out, and skips updating entirely (so the colorgrade is not changed) when the heatwave is invisible.
=> Heat Wave effect not affecting color grade when disabled

Ahorn/lang/en_gb.lang, Ahorn/triggers/speedBasedMusicParamTrigger.jl, SpringCollab2020Module.cs, SpringCollab2020Session.cs, Triggers/SpeedBasedMusicParamTrigger.cs
Request from Thegur90:
> the ideal scenario is a trigger which has:
2 numeric values - maximum and minimum.
fmod parameter textbox
activate/deactivate checkbox
>
> when on activate:
the trigger will constantly get the speed value of maddy and output it to the fmod param. on my end ill set the fmod parameter values to match the speed.
if it's outside the min/max value boundary it will output the min/max values respectively.
>
> when on deactivate:
the trigger will output the minimum value all the time.
>
> all effects should work until you touch another trigger, as having a giant trigger on the entire map isn't ideal.
This PR is... pretty much that.
=> Speed-Based Music Param Trigger

Ahorn/lang/en_gb.lang, Ahorn/triggers/flagToggleCameraTargetTrigger.jl, Ahorn/triggers/flagToggleSmoothCameraOffsetTrigger.jl, Triggers/FlagToggleCameraTargetTrigger.cs, Triggers/FlagToggleSmoothCameraOffsetTrigger.cs
For special use cases in lobbies. Since smooth offsets can be used as regular ones as well, I didn't make a "flag toggled camera offset trigger".
=> Flag-toggled camera target triggers and smooth camera offsets

Ahorn/entities/staticPuffer.jl, Ahorn/lang/en_gb.lang, Entities/StaticPuffer.cs, SpringCollab2020Module.cs
Just a puffer fish, except it doesn't wave around. Requested for a heart side.
The IL hook resets the sine wave just after it is randomized, because its value is used right after in the constructor. This way, the static position of the puffer is the one chosen in Ahorn. Then, the StaticPuffer constructor removes the SineWave component from the entity, so the wave stays at 0 all the time and the puffer doesn't move.
=> Static Puffer

Ahorn/triggers/leaveTheoBehindTrigger.jl, SpringCollab2020Module.cs, Triggers/LeaveTheoBehindTrigger.cs
This is a trigger to enable leaving Theo behind when leaving the current room, to be used in a heart side.
It's kind of a bootleg of [Disposable Theo Trigger](https://gamebanana.com/gamefiles/11138), except it's implemented quite differently, and doesn't show up in Mod Options.
Issues related to TASing were reported with Disposable Theo enabled: there is a 1 frame timing difference in screen transitions desyncing TASes when the mod is on. Since having a dependency for a single trigger used once in the collab seems like a shame, I decided to reimplement it in the collab helper: the implementation is vastly different, but the overall behavior of the trigger is the same.
=> Leave Theo Behind Trigger

Ahorn/triggers/pauseBadelineBossesTrigger.jl, Triggers/PauseBadelineBossesTrigger.cs
This trigger prevents Badeline from attacking the player while they are inside it.
This works by removing the attackCoroutine from the Badeline bosses for the duration the player is in the trigger. Before removing the routine, the trigger waits for Badeline to be idle, because we don't want to interrupt it mid-attack.
=> Pause Badeline Bosses Trigger

Ahorn/entities/groupedTriggerSpikes.jl, Ahorn/lang/en_gb.lang, Entities/GroupedTriggerSpikes.cs
This was requested on Discord, because it just looks weird.
=> Option to display grouped trigger spikes behind move blocks

Ahorn/entities/variableCrumble.jl, Ahorn/lang/en_gb.lang, Entities/VariableCrumbleBlock.cs
- The "texture" attribute was not applied at all. I checked all collab maps and changed the "cliffside" crumble blocks to "default" ones so that their look does not change. Only 1 map was impacted (Tortoise's) and the author agreed with this.
- Added a respawnTimer attribute, so that a dependency on Max Helping Hand for _that one_ attribute isn't required.
=> Variable Crumble Block: fix the 'texture' attribute + add 'respawn time' attribute

Ahorn/lang/en_gb.lang, Ahorn/triggers/badelineBounceDirectionTrigger.jl, SpringCollab2020Module.cs, Triggers/BadelineBounceDirectionTrigger.cs
This is a simple trigger you place over a Badeline boss node to determine if Madeline gets pushed to the right or to the left when hitting Badeline.
=> Badeline Bounce Direction Trigger
